### PR TITLE
Updated Italian Translation

### PR DESCRIPTION
**Pull request by MarioVillani**
Improved some phrases, typo corrections.

### CODE REVIEW

**Comment by droidmonkey** [comment]
Translation work happens over on Transifex

**Comment by MarioVillani** [comment]
@droidmonkey seems like i cannot join without using a business email. am i forced to do so? thanks

**Comment by droidmonkey** [comment]
User your github account

**Comment by MarioVillani** [comment]
I did so but it continously told to use a business email.
Seems like first signup attempt went not good from their side, after revoking and relinking Transifex third-party app in my account registration went fine. Thanks

**Comment by MarioVillani** [comment]
@droidmonkey my changes have been replicated on Transifex as suggestions. Let me know if everything is ok for you :)

**Comment by droidmonkey** [comment]
Would you like to be a reviewer on transifex for italian?

**Comment by MarioVillani** [comment]
> Would you like to be a reviewer on transifex for italian?

Sure.

**Comment by MarioVillani** [comment]
@droidmonkey  Thanks, i've updated and reviewed all Italian strings for KeePassXC-Browser.

**Pull request closed without merging**
