### PR TITLE
Better identification for Shadow DOM in Improved Input Field Detection

### LINKED ISSUE #446: Support Polymer Shadow DOM logins
I tried to use keepassxc browser extension for my home assistant login, but it can't detect the login fields. Neither automatically nor with "custom login fields" option. I think this is because of the polymer login fields using shadow dom like described in https://github.com/home-assistant/home-assistant-polymer/issues/1622.

## Expected Behavior

Browser extension should detect login fields automatically

## Current Behavior

Browser extension does not detect login fields and login fields and "custom login fields" is also not working

## Steps to Reproduce (for bugs)

* Spin up a docker container with home assistant and try to login or
* Use this example page http://youssef06.github.io/polymer-login-form/demo.html (should be the same issue I think)

## Debug info

KeePassXC - Version 2.4.0
Revision: c51752d
KeePassXC-Browser Version: 1.3.2
Browser: Chrome

Libraries:
- Qt 5.12.1
- libgcrypt 1.8.4

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

### PR DESCRIPTION
**Pull request by varjolintu**
Includes the following improvementes:
- Instead of traversing each child with `.childNodes()` rely on the TreeWalker API for retrieving all elements under the target.
- Add a proper check for `Element` Shadow DOM using `openOrClosedShadowRoot` and `dom.openOrClosedShadowRoot()`.
- Support Shadow DOM's under Document Fragments.

A few test sites:
https://e.sfcu.org/sfcuonline/uux.aspx#/login
https://login.minid.no/ (accesible via https://venterom.skatteetaten.no/?c=digdir&e=skatteetaten&t=https%3A%2F%2Fskatt.skatteetaten.no%2Fweb%2Fminside%2F)

Fixes #446.

### CODE REVIEW

**Review by droidmonkey — APPROVED** [review]

**Comment by vbeffa** [comment]
Hi @varjolintu, I've been successfully auto-filling https://e.sfcu.org/sfcuonline/uux.aspx#/login until today, and now it seems to not be working again. I tried removing and adding a custom site preference with "Improved Input Field Detection" checked. Anything else I can try?

**Comment by varjolintu** [comment]
@vbeffa https://github.com/keepassxreboot/keepassxc-browser/pull/2659

**Comment by vbeffa** [comment]
Thanks, is 1.9.10 released yet? If I go into KeePassXC-Browser settings and click `Check for updates`, it only seems to check KeePassXC. Similarly under Manage Your Extensions if I check for updates, I don't see an update.

**Comment by varjolintu** [comment]
@vbeffa The latest version is 1.9.9.3, but 1.9.9.4 is hitting the stores as we speak. Your browser handles the extension updates. 1.9.10 has not been released yet.

You can follow the releases here: https://github.com/keepassxreboot/keepassxc-browser/releases

**Comment by vbeffa** [comment]
OK, thanks.

**Pull request merged**
