### PR TITLE
UX improvements

### LINKED ISSUE #339: Won't fill multiple passwords on multiple pages
## Expected Behavior

The [ProtonMail login page](https://mail.protonmail.com/login) is composed of:
1. Page one: the username and password
2. Page two (optional): the OTP (if a 2FA has been activated)
3. Page three (optional): the mailbox password (if you have this particular [password enabled](https://protonmail.com/support/knowledge-base/switch-two-password-mode/))

On page two, I can use <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd> to fill the password.

One page three, I expect the _Mailbox password_ field to be filled.

## Current Behavior

On page three, I cannot find a way to autofill the _Mailbox password_ field (which is different from the account pass word from step 1).

## Possible Solution

I'm not sure how I am supposed to play with the UI, the `storage.js`, or the `KPH:` attributes in my KeePass custom fields.

I am currently using KeePass with the [KeePassNatMsg](https://github.com/smorks/keepassnatmsg) plugin. Maybe I must use KeePassXC.

A documentation may help, or maybe it is a PEBCAK problem.

## Debug info

KeePass - 2.40
[KeePassNatMsg](https://github.com/smorks/keepassnatmsg) plugin - 2.0.3.0
KeePassXC-Browser - 1.3.0
Operating system: Win
Browser: Firefox

### LINKED ISSUE #350: Allow to add new entry without username
## Expected Behavior
When updating a password on the site, KPXC (browser extension) correctly detects an updated password and flashes red. When opening the extension bubble, allow me to click 'New' to create a new entry. If necessary, open the main KPXC window to allow me to add the username, or have a text field in the extension bubble itself.

## Current Behavior
Upon opening the extension bubble, the 'new' option is greyed out for it didn't detect any username.

Reasoning: I'm currently in a migration process (from browser to KPXC), and add an item whenever I use a service (that I use irregularly). Already logged in to a site I update the password, making use of KPXC's generation mechanism. Currently I have to copy-paste the generated password to the 'new entry' screen of the main KPXC window.

## Debug info
KeePassXC-Browser Version: 1.3.0
KeePassXC Version: 2.3.4
Operating system: Ubuntu 18.04
Browser: Firefox

### LINKED ISSUE #415: Doesn't find all form values (onba.ch)
## Expected Behavior
Should fill the correct values (username and password) into their respective fields at:
https://www.onba.ch/login/login?bank=sgkb

## Current Behavior
It does not find the fields to enter the credentials. When manually selecting "Fill Username and Password", only the username is set. Filling the password afterwards results in the message "no password field found".
Also, using the manual field selector, after selecting the username field as username, it doesn't allow me to select the password field; it is greyed out and not active.

## Steps to Reproduce (for bugs)
1. Have credentials at https://www.onba.ch/login/login?bank=sgkb
2. Try to autofill all credendials.
3. Only username is filled
4. Password is missing.

## Debug info

KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.2
Operating system: Linux
Browser: Chrome and Firefox

### LINKED ISSUE #538: Redetect credential fields when fill username and password is clicked
## Expected Behavior
When the user clicks fill username and password from the right click menu and no credential fields are detected yet, KeePassXC-Browser should redetect the credential fields before filling username and password.

## Current Behavior
When the user clicks fill username and password and the credential fields aren't detected yet, nothing happens. This can be confusing because the user clearly sees the credential fields because he has right clicked on them.

## Steps to Reproduce (for bugs)
1. Go to a page where the credential fields only appear after you have clicked on something.
2. Right click -> Fill username and password.
3. Nothing happens.

## Debug info
KeePassXC - 2.4.1
KeePassXC-Browser - 1.4.3
Operating system: Linux
Browser: Firefox

### LINKED ISSUE #550: Autocomplete dropdown position changes depending on page scroll position
I noticed that sometimes after clicking the username field the autocomplete dropdown options aren't shown properly below the username field. It looks like whether or not it shows properly depends on how far up or down from the login fields the page is scrolled.  I saw this happening on an internal page but I'm pretty sure it could happen on other websites. I've even seen the dropdown options shown way above the login fields.

### LINKED ISSUE #568: Unable to fill password
## Expected Behavior
Reopen keepassxc via plugin, I can fill the password correctly on the webpage

## Current Behavior
If my Keepassxc database is down, I reopen the database in the plugin, but I can't fill the password correctly.
If I want to use it normally, I can only delete the connection and recreate the new connection.

image

## Possible Solution
reason for the bug

## Steps to Reproduce (for bugs)
1. close keepassxc db
2. open web url and click keepassxc plugin
3. reopen keepassxc db
4. fill password

## Debug info
keePassXC - 2.4.3 
KeePassXC-Browser - 1.4.6
Operating system: Mac
Browser: Chrome

## Recurring operation
github

### LINKED ISSUE #574: Allow to save browser passwords in root
I would like to save the browser password directly in root instead of in a group. It doesn't seem to be possible.

Btw, what is the benefit/reason of storing browser passwords in a different group?

### LINKED ISSUE #576: update password broken in change password form
When having a form like the following to change the password, updating the password from the browser extension doesn't work properly.

```
Current
New
Confirm new
```

## Expected Behavior
`New` password is saved.

## Current Behavior
`Current` password (the old one) is saved.

## More info

Related to https://github.com/keepassxreboot/keepassxc-browser/issues/575

## Debug info

KeePassXC - 2.4.3
KeePassXC-Browser - 1.4.6
Operating system: Linux (openSUSE Leap 15.1)
Browser: Mozilla Firefox 60.7.2

### LINKED ISSUE #584: Missing quotes in defaultSettings
Hi,

keepassxc-browser/background/page.js misses quotes around the default update interval: checkUpdateKeePassXC: 3,

should be

checkUpdateKeePassXC: '3',

Cheers - Bruno

### LINKED ISSUE #598: login.vivaldi.net This site cannot save credentials
## Steps to Reproduce (for bugs)
1. Visit https://login.vivaldi.net/authenticationendpoint/login.do
2. Enter your username and password and click "Sign in".
3. The KeePassXC-Browser extension does not prompt to save, and the icon of the toolbar has not changed. As a result, the website login credentials cannot be saved.

## Debug info

KeePassXC - 2.4.3
KeePassXC-Browser -1.4.7
Operating system: Win 7
Browser: Vivaldi

### PR DESCRIPTION
**Pull request by varjolintu**
This PR aims to improve the user experience of the extension. Mainly this is going to solve the following problems:
1) Unlock the database from username field (and open the autocomplete immediately after)
2) Unlock the database from password field (if it's the only input)
3) Change password generator icon to an additional feature
4) Focus on tasks that are more common (instead of less common, like generating the password)
5) Use of icons (use the same key icon everywhere or separate lock icons)

All comments and further improvements are very welcome.

Fixes #339.
Fixes #350.
Fixes #415.
Fixes #538.
Fixes #550.
Fixes #568.
Fixes #574.
Fixes #576.
Fixes #584.
Fixes #598.

### 1. Changes to username fields
Every username field (or a password field if it's a single one) has a username icon. Database can be unlocked by clicking the icon. If a database is already open, single credentials are automatically filled when clicked. If multiple credentials are available, autocomplete menu is shown instead. Clicking the input field directly shows the autocomplete menu, just like in previous versions.

Only one of these icons are shown even if there's multiple possible input fields visible.

Screen Shot 2019-08-22 at 15 19 07

See it in [action](https://www.dropbox.com/s/xq2t3hw0nkze6qr/username_field.mp4?dl=0).

### 2. Changes to password generator and its icon(s)
Password generator icons are now invisible by default, and the Settings page's `Activate password generator` settings has been changed to `Activate password generator icons`. Also the context menu item for showing the icons has been removed. Password generator can still be shown via the context menu or keyboard shortcut even if the icons are invisible.

As using password generator feature is a less common task, it makes sense to hide it from the user and give more focus to the username field and credential filling instead.

### 3. Changes to notifications
The extension doesn't use much notifications, but when needed, using the official Notification API has a limited functionality on some browsers (e.g. showing button), plus notifications can be shown over browser toolbar icons which affects usability. 

All notifications are shown in the DOM instead, and these will disappear automatically after five seconds, or can be clicked away.

Screen Shot 2019-09-17 at 19 13 13

### 4. Changes to credential saving
In the previous versions, credential saving has been unreliable. Using the popup for saving credentials is a complex way to do it, and requires lots of extra code just to maintain some kind of usability for it. This PR modifies the process in a way that credentials are saved using a banner that is directly shown in the DOM.

All related features from the popup icon is removed with Settings page options for redirects etc, which are no longer needed at all. Even if the web page has some redirects, the credentials are saved temporarily to the background script where it can be retrieved when showing the credential banner.

Screen Shot 2019-09-17 at 19 13 34

The banner feature can be seen [here](https://www.dropbox.com/s/olkqxd3exq138o9/banner.mp4?dl=0) (video).

### 5. Changes to Site Preferences
When the extension detects a page with a single username field, the popup will show an additional message that allows user to add the current site to Site Preferences with Username-only option enabled. Fields are also redetected automatically, so the page is ready for use right after the addition.

Screen Shot 2019-09-03 at 14 08 52

A new file `sites.js` is introduced in the content scripts. It holds a list of certain sites that needs special URL handling, and it also includes a function that allows common username-only sites to be added to Site Preferences by default (however, this feature is not used yet, as the list must be updated).

### 6. Changes to the password generator
The password generator is simplified and much more compact.

Screen Shot 2019-09-17 at 19 14 24

### Current progress:
- [x] Add lock/unlock icon to username field
- [x] Clicking the lock icon unlocks the database and fills single credentials
- [x] Popup shows an option to add a site to Site Preferencs with "Username-only Detection" when needed
- [x] Clicking the unlock icon fills single credentials automatically, autocomplete menu is shown if multiple
- [x] Credentials are filled (or shown if multiple) automatically after unlock
- [x] Change password icon behaviour
- [x] Improve credential saving/updating workflow
- [x] Replace notifications with a new implementation
- [x] Show notifications on successful update, canceled operation and error situations
- [x] Add support for `success`, `canceled` and `error` states when updating credentials
- [x] Remove remember popup behaviour
- [x] Modify button and alert colors to match Bootstrap 4 colors
- [x] Keep autocomplete position when scrolling
- [x] Refactor most of `Promise.then()` to `async/await`
- [x] Simplify the password generator
- [x] Test everything

### CODE REVIEW

**Comment by phoerious** [comment]
Perhaps the lock icon could also show a list of all locked databases, so I can select the one I want directly from the browser extension before the unlock dialogue is shown.

I also think that the password generator widget should not only be moved to a less prominent place, but also get a visual makeover, maybe as part of #322.

**Comment by droidmonkey** [comment]
Do you mind posting some screenshots of the improvements?

**Comment by varjolintu** [comment]
FYI: I'll continue working with this PR after the next release.

**Comment by julian-klode** [comment]
I feel like bitwarden handles the case of adding/updating credentials somewhat better, by showing you a top bar on the page rather than a non-actionable notification + a blinking extension icon:

Screenshot from 2019-06-08 17-58-33

I found one webpage where this did not work correctly, though, and the bar disappeared after some forwarding. I don't remember how keepassxc behaved. Chrome's own password storage was fine.

**Comment by varjolintu** [comment]
I agree that creating/updating credentials could be better if it would be made without the icon stuff. Same with the HTTP Basic Auth that often requires using the icon.

**Comment by varjolintu** [comment]
@julian-klode I just added a similar banner with the latest commit. It's not finished yet (lot of comments in the code etc) but you can see the workflow here: https://www.dropbox.com/s/olkqxd3exq138o9/banner.mp4?dl=0

**Comment by julian-klode** [comment]
@varjolintu Nice work

**Comment by varjolintu** [comment]
With the latest two commits the following changes are made:
- Notifications are now displayed in the web page instead of browser API notifications
- Credential Banner can return to the "main menu"
- The whole remember credentials popup is removed with all of its settings

**Comment by varjolintu** [comment]
I decided to remove two features from this PR:
- Improve HTTP Basic Auth workflow
- Add a message when fields are redetected

First, HTTP Basic Auth workflow is quite hard to do in the DOM because no actual page content hasn't been loaded. We must find another away to improve the login dialog for that.

Second, showing the field count when Redetect credential fields button is used is going to need another PR I've been making in the background implemented first. Shortly, it's simplyfying the code and getting us away from the Promise-callback based code to a async/await style code. It makes things much more easier to read.

**Comment by droidmonkey** [comment]
Please let me know when this is ready for end-to-end testing

**Comment by varjolintu** [comment]
@droidmonkey Sure. I'm currently in a testing phase where I try to change every password from my database to see if really works. Still perfecting it.

**Comment by sebast889** [comment]
@varjolintu wouldn't it be better to make clicking the unlock icon just lock the database? I know there's the lock option in the popup but it's seems quicker and more relevant for the unlock icon. Also will help the use case of wanting to open the database to log into a single website by doing everything easily from just username textbox (click the lock icon, open database, click field and choose credential to fill, click unlock icon to lock database again)

**Comment by varjolintu** [comment]
@sebast889 I think that's not a better use of the icon. We would like to make those things easier that are used most frequently, and of course filling the credentials is the most used feature. Locking the database instead of a credential fill doesn't sound very handy (even if it would be more logical at first). You can already click the field and choose credential to fill, but because users mostly have single logins for site, this kind of one-click-fill is quite handy.

**Comment by sebast889** [comment]
What about changing the lock icon behavior so that once the database is open it fills in the credential if there is only one? Is that possible? Makes it even easier than having to click an icon.

**Comment by varjolintu** [comment]
@sebast889 That change needs some extra stuff to the background scripts (needs another big PR I've been making). Now you have to click the icon after unlock.

**Comment by sebast889** [comment]
If it can be done then great because it makes it even easier to use, to fill in single logins without needing another click and opens up the unlock icon to be used for another function (e.g. for locking the DB). I also don't think people opening their DB temporarily to just log into a single website then locking the DB is an uncommon use case either, which the icon would help with.

Do you think a different icon for the autofill action would be better? In case the unlock icon is ever used for locking DB later and the unlock icon doesn't really seem intuitive for "fills in credential".

**Comment by varjolintu** [comment]
At first the icon was different, and I'm tempted to change it to https://forkaweso.me/Fork-Awesome/icon/user/, like it was at first. And maybe instead of a lock/unlock icon it could be that user icon and https://forkaweso.me/Fork-Awesome/icon/user-o/ for a locked database.

Need to think this over. Any suggestions are very welcome.

**Comment by varjolintu** [comment]
It's possible that I include the major async/await refactor to this PR. Many of the features would be easier to implement using async/await instead of Promises.

**Comment by droidmonkey** [comment]
What about a custom font icon that is a simplified version of the KeePassXC logo?

**Comment by varjolintu** [comment]
@droidmonkey That's possible too. I'm not using those icons directly from the font (because then the fonts must be added to content scripts which is a big no) but the plain SVG's.

**Comment by droidmonkey** [comment]
Ah even better!

**Comment by varjolintu** [comment]
The latest https://github.com/keepassxreboot/keepassxc-browser/pull/351/commits/31a455ddc26fc0ed75934085d6fed5e67582d264 is a big one. It gets rid of the old callback based event system and replaces it with Promises. Also, most of the `Promise.then()` stuff is replaced with `async/await` which makes the asynchronous code easier to manage. Now it's possible to fill single credentials automatically using the username field icon, plus the new credential banner is shown always (`Promise.then()` was not so reliable).

**Comment by varjolintu** [comment]
@droidmonkey Here's a screenshot using a modified KeePassXC icon. I'm not quite sure if those icons are distinguishable enough because only the color changes.

Locked:
locked
Unlocked:
unlocked

**Comment by z3ntu** [comment]
The buttons in this bar are a bit offset:
Screenshot_20190728_123322

**Comment by varjolintu** [comment]
@z3ntu Which site does that? Gotta do some heavy CSS tuning.

**Comment by z3ntu** [comment]
This was on sofort.com (more precisely https://www.sofort.com/payment/multipay/go/ ), I hope the same CSS is injected on the error page when trying to visit it directly^^ When I see it on another site, I'll let you know.

**Comment by varjolintu** [comment]
Another option would be to use https://forkaweso.me/Fork-Awesome/icon/user/ and https://forkaweso.me/Fork-Awesome/icon/user-o/.

**Comment by keunes** [comment]
Wow, that's some great improvements! :D

About the new unlock/fill KPXC icon: I'm not sure this colour-only change between states complies with the Web Content Accessibility Guidelines (WCAG) standards. I'm on mobile right now and can't really research, but to be sure I'd just have the icon change.

Also, shouldn't all notifications/warnings have a similar lay-out? As in: in the screenshots above the messages in 3 and 4 have a different design. Now you're getting rid of the pop-up it'd be nice to unify the approach to both types.

**Comment by varjolintu** [comment]
@keunes I think also that just changing the icon colour is not enough. Unlock/lock icons are more informative but then again, the popup dialog uses the lock icon as "database lock", and now the username field uses the same icon as "open database". So it does the opposite, which can cause some confusion.

The credential bar is not a normal notification/warning, if that's what you meant.

**Comment by keunes** [comment]
> the popup dialog uses the lock icon as "database lock", and now the username field uses the same icon as "open database". So it does the opposite, which can cause some confusion.

Buttons represent actions, i.e. they should indicate what they do. In that sense, yes, using the same icon as used for locking the database could be confusing. But since the action is the opposite, why not take the 'opposite' icon also; https://forkaweso.me/Fork-Awesome/icon/unlock-alt/ ? Then when unlocked, the icon could be a pencil (as is) to indicate another click would write something (i.e. fill the fields).

> The credential bar is not a normal notification/warning, if that's what you meant.

I don't think we're on the same page, here. What I meany is that notifications (screenshot 3 in the original post) should have the same layout/struccture as the credential banner (screenshot 4 in the original post): full width, KPXC logo on the left, then the message left-aligned, (white space) action (in most cases just a cross for 'close') right-aligned in the bar. Either the word 'Error' or 'Warning' or 'Info' could then have a background (red, yellow, or blue respectively), or the full var could take this colour. Again, sorry in case of confusion, but I'm on mobile so can't make a mock-up.

**Comment by varjolintu** [comment]
> Buttons represent actions, i.e. they should indicate what they do. In that sense, yes, using the same icon as used for locking the database could be confusing. But since the action is the opposite, why not take the 'opposite' icon also; https://forkaweso.me/Fork-Awesome/icon/unlock-alt/ ? Then when unlocked, the icon could be a pencil (as is) to indicate another click would write something (i.e. fill the fields).

That's one option, yes. I would like to have more opinions about the icons from other people as well.

> I don't think we're on the same page, here ;) What I meant is that notifications (screenshot 3 in the original post) should have the same layout/structure as the credential banner (screenshot 4 in the original post) to create consistency/recognisability for the user: full width, KPXC logo on the left, then the message left-aligned, (space,) and the action (in most cases just a cross for 'close') right-aligned in the bar. Either the word 'Error' or 'Warning' or 'Info' could then have a background (red, yellow, or blue respectively), or the full banner could take this colour. Again, sorry in case of confusion, but I'm on mobile so can't make a mock-up.

I think this is a good idea, but at the same time I'm not very comfortable showing a notification that takes the whole width of the current page. Need to think this one too.

**Comment by varjolintu** [comment]
Username field icons are now:

Screen Shot 2019-08-22 at 15 18 11 for unlocked.

Screen Shot 2019-08-22 at 15 18 02 for locked.

**Comment by z3ntu** [comment]
The "update" button in the "username or password changed" banner doesn't seem to work.

**Comment by varjolintu** [comment]
> The "update" button in the "username or password changed" banner doesn't seem to work.

Interesting. What page does it? Any errors in the console?

**Comment by z3ntu** [comment]
It was on https://aur.archlinux.org/login and I didn't see any errors in the console (also of the "background page" from the extension or whatever it's called)

**Comment by keunes** [comment]
> [Screen Shot 2019-08-22 at 15 18 11] for unlocked.

Does this button fill in the user's details, as you described earlier? If yes, be aware that the button doesn't really indicates this, so I'm not sure end-users will really use the button. In case the current 'drop-down' with the available accounts (when activating a field) is removed, I don't think this will work as a replacement. A lot of ifs, but just wanted to share :)

**Comment by varjolintu** [comment]
> Does this button fill in the user's details, as you described earlier? If yes, be aware that the button doesn't really indicates this, so I'm not sure end-users will really use the button. In case the current 'drop-down' with the available accounts (when activating a field) is removed, I don't think this will work as a replacement. A lot of ifs, but just wanted to share :)

Yes, clicking it will fill single credentials, and it will show the old listing if there are more than one credentials available. Also, clicking the input field works like it used to.

That's the hard part when choosing the proper icon: how to indicate that it will do something. Now only the icon title gives a hint (when hovering with mouse). Of course this must be added to the documentation.

**Comment by varjolintu** [comment]
@z3ntu I couldn't reproduce the problem. I had a credentials for the page, then entered a different username and used the context menu to trigger the credential saving. Update button worked normally.

**Comment by z3ntu** [comment]
Weird, I'll report any things I see in the future :)

**Comment by varjolintu** [comment]
The popup has now a new setting that allows user to add the site to Site Preferences with Username-only option enabled. This triggers if the site has only one username field detected.

Otherwise, this PR is now in the testing phase. No new features will be added. Thanks everyone for testing the PR, and all the ideas. I appreciate it.

**Comment by droidmonkey** [comment]
Couple issues right off the bat:

* On the extension settings page, when connecting to a database, it does not automatically refresh the list after the connection is made. This makes it seem like the database connection failed.

* On a freshly opened KeePassXC instance, pressing the reload button in the extension popup causes the popup to "go blank"
image

* During a "single username field" login flow, the password field on the second page does not have the KeePassXC fill icon.

* The password generator does not appear above floating div elements. Probably need to give it a very high "z-index"

* The password generator still looks very dated and confusing. Do we really need to show the number of bits? Checkbox is on a different line from text. The buttons on the bottom have a weird gradient and it is unclear which one is the "default option".
image


The new KeePassXC icon auto-fill button is AWESOME.

**Comment by varjolintu** [comment]
@droidmonkey Thanks for reporting the issues! I agree that the password generator needs some tuning.

**Comment by whisdol** [comment]
Awesome improvements, I really like this!
I'll start poking around it a little bit, one little UX bug for now:
When the credential list with only one entry is displayed below a username field, clicking the username icon fills in the credential, but does not close the credential list. (Workflow: Click into username field, then click username icon.)
autofill

**Comment by phoerious** [comment]
I love the new button, too. It finally makes the whole thing usable if you have a lock timeout set for your database. We should see if we can either use the DatebaseUnlockDialog instead of showing the main window or fix the focus situation. Right now, the main window opens, but I need to activate it first in the task bar, which is inconvenient.

**Comment by varjolintu** [comment]
@phoerious Using `DatabaseUnlockDialog` would be much nicer indeed. I'll see what I can do.

I have a branch that does some adjusting to the detection: https://github.com/keepassxreboot/keepassxc-browser/tree/fix/detect_fields_after_form_removal. Can you provide some URL's that does this so I can test the behaviour? Thanks.

**Comment by phoerious** [comment]
One would be https://www.bahn.de/.
The work around is to try to login without credentials, which then brings you to another page with proper login fields.

**Comment by varjolintu** [comment]
> One would be https://www.bahn.de/.
> The work around is to try to login without credentials, which then brings you to another page with proper login fields.

Oh, these are tricky because here the parent element is added with an extra class `open` when hovering with mouse. I added a new `attributeFilter` to `MutationObserver` with `class`. If that kind of change is detected, and the class holds a `form` or `input` element, it redetects the credential fields for the page. This way it ignores any changes detected to a "normal" class.

**Comment by varjolintu** [comment]
@droidmonkey I fixed the bugs you mentioned. The second page password input thing and password generator update will be next.

**Comment by varjolintu** [comment]
@whisdol The Autocomplete menu was also kept visible when choosing credentials from the popup, so that's also fixed now :)

**Comment by varjolintu** [comment]
@droidmonkey Simplified the password generator and adjusted some of the CSS to prevent page's modifications to it. Does it look any better?

Screen Shot 2019-09-09 at 16 05 17

**Comment by droidmonkey** [comment]
Fantastic!!

**Comment by varjolintu** [comment]
@droidmonkey The Google login page should now show the username field icon on the password page too. Plus it fixes the Protonmail mailbox password issue too.

**Comment by YaLTeR** [comment]
Last time I checked, Lastpass had their "show password" icon in the exact same place as the current keepassxc-browser "generate password" icon, which made it really hard to use Lastpass (I need that sometimes for someone other than me). Will this update solve this issue somehow?

**Comment by varjolintu** [comment]
@YaLTeR It's not recommended to use multiple password manager extensions in the browser simultanously, but of course I can test that out. It could be possible to check if the icon collides with another icon/picture and move it further to the left if needed.

**Comment by YaLTeR** [comment]
Oh no, it's not an extension, it's the actual Lastpass website.

**Comment by varjolintu** [comment]
@YaLTeR Actually, the password generator icon is not even enabled by default after this PR. But, I can still try to make some adjustments that the icon will not go over another icon.

**Comment by droidmonkey** [comment]
Repeating my test on Google login with the split username/password field causes the Allow/Deny dialog to show about 6 times.

**Comment by varjolintu** [comment]
@droidmonkey I fixed the other bugs, with Allow/Deny stuff takes some more time. I need to think one previous fix again once more.

**Comment by droidmonkey** [comment]
There seems to be an issue with the extension retaining credentials after allow/deny. It asks repeatedly even without page refresh

**Comment by varjolintu** [comment]
@droidmonkey One part of the reason is that every content script (frame) is doing the requests simultaneously.

**Comment by varjolintu** [comment]
@droidmonkey Could you give me the site where the password generator bugs happen? I could test the fixes really work.

**Comment by droidmonkey** [comment]
I can't share the website since its an admin backend, unfortunately.

**Comment by varjolintu** [comment]
@droidmonkey Pushed some changes. Please try if it fixes the issues.

**Comment by varjolintu** [comment]
Final changes have been pushed. I also updated the images to the first message.

**Comment by droidmonkey** [comment]
When KeePassXC is not running I received a pop-out error message "No logins found!". Upon switching tabs the icon reverted to the "Not Connected" icon and it didn't react. I hadn't connected to the application at all, yet the extension was acting like I was already connected. Might need to check the initialization of variables.

**Comment by varjolintu** [comment]
@droidmonkey Made the fixes.

**Comment by droidmonkey** [comment]
Awesome!

**Comment by droidmonkey** [comment]
I've retested and everything is working, all of my issues are fixed. I think this is ready for prime time.

**Comment by z3ntu** [comment]
I also have no complains after using this for a few months(?) :)

**Comment by varjolintu** [comment]
I'll merge this to develop and update the translation file. Let's wait a couple days for updates.

**Pull request merged**
