### PR TITLE
[WIP] Linting

### PR DESCRIPTION
**Pull request by varjolintu**
Preliminary support for eslint.
`npm run lint`

### CODE REVIEW

**Comment by thetric** [comment]
What about a `package-lock.json` or `yarn.lock` file?

**Comment by rugk** [comment]
This needs more prio. That is totally required… :smiley:

**Comment by varjolintu** [comment]
Oh yes, it is. Still working on the ruleset.

**Comment by varjolintu** [comment]
Closing this because I'm making new PR with `.eslintrc` instead, that can be used straight with multiple editors and IDE's.

**Pull request closed without merging**
