### PR TITLE
Revert #371

### PR DESCRIPTION
**Pull request by varjolintu**
#371 fixed some race conditions, but it's not working properly. Another type of solution is needed. The change needs to be reverted.

Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/386.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/402.

### CODE REVIEW

**Comment by varjolintu** [comment]
Doing some minor fixes to this PR, hold on.

**Comment by whisdol** [comment]
Even with this fix (68bcdd1), the following workflow does not always work for me on https://www.kvb.koeln/app/index.html (scroll down and click "Login", the URL for the database entry is https://kvb.mobilesticket.de):
1. Start Firefox, KeePassXC
2. Open https://www.kvb.koeln/app/index.html, click "Login" so the credential fields are shown
3. Click Reopen Database in the extension
4. Enter Password in KeePassXC, return to Firefox
5. Click "Redetect Credential Fields"

It seems hard to reproduce now, but it definitely failed the first time I tried it. The autocomplete suggestions were only shown after switching tabs. I then tested it 5 more times, and the credentials were loaded as expected after redetecting the credential fields.

However, the 5. step should ideally not be necessary (but maybe that's not in the scope of this PR?).

**Comment by varjolintu** [comment]
@whisdol I'll check those pages if I can reproduce it. It's preferred that everything should work without using the "Redetect credential fields" button.

**Comment by whisdol** [comment]
Ok, I found a more reliable way to reproduce it:
1. Start Firefox
2. Open website (also tried this on https://www.dkb.de/banking/finanzstatus?$event=init, so I don't think it's necessarily restricted to websites with frames)
3. KeePassXC-Browser should say "Timeout or not connected to KeePassXC."
4. Start KeePassXC-Browser, unlock database
5. Return to Firefox
6. Click "Reload" in the extension, it should now be connected
7. Click "Redetect login fields"

With this workflow, credentials are never loaded for me.

**Comment by varjolintu** [comment]
@whisdol I could not reproduce the latter one, but the first one does happen.

**Comment by varjolintu** [comment]
You could try (or merge) https://github.com/keepassxreboot/keepassxc-browser/pull/358 because it's related to the issue you are describing.

**Comment by varjolintu** [comment]
@whisdol Great! I'll check the popup behaviour.

**Comment by varjolintu** [comment]
I ended up to a solution that reverts the #371. It just doesn't work properly and in the end it causes more problems than it solves. A much bigger refactor is needed for this, and it makes sense only if it's made after #128 is merged.

@droidmonkey Please review this again.

Sorry for the inconvenience guys.

**Pull request merged**
