### PR TITLE
Adjust the popup size when needed. Change upper row buttons to icons.

### PR DESCRIPTION
**Pull request by varjolintu**
- Changes the upper row buttons to icons for better scaling with Firefox's pinned popup. The old button texts are visible as tooltips.
- Adjusts the popup width when needed. With Chromium based browser popups have no other width than the content if it's not specified.

Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/721.

### CODE REVIEW

**Comment by droidmonkey** [comment]
The hand icon is rather ambiguous. Any other choices or maybe a short text like "Custom Fields"

**Comment by varjolintu** [comment]
@droidmonkey I'd prefer an icon. Any suggestions? The old icon without a text was not very informative.

**Comment by droidmonkey** [comment]
How about something like this with the hand on top instead of the cursor:

https://materialdesignicons.com/icon/form-textbox-password

**Comment by varjolintu** [comment]
Something like that could work.

**Comment by varjolintu** [comment]
Maybe something like this? I took the TOTP icon as the base.
Screenshot 2022-03-12 at 11 34 27

**Comment by droidmonkey** [comment]
That's pretty nice! Kind of mickey mouse looking thigh

**Comment by varjolintu** [comment]
The transparent style:
Screenshot 2022-03-12 at 14 57 26

**Comment by droidmonkey** [comment]
Personally think that's perfect

**Comment by varjolintu** [comment]
Let's keep that then.

**Comment by varjolintu** [comment]
Oh, one more option, if we want to keep the icon "filled". But maybe that's too much Mickey Mouse too.

Screenshot 2022-03-12 at 17 14 24

**Comment by droidmonkey** [comment]
Oh the final version is hawt

**Comment by varjolintu** [comment]
Or we could go dark.. difficult decisions:
Screenshot 2022-03-12 at 19 30 03

**Comment by varjolintu** [comment]
Uh oh. This is totally broken after the removal of jQuery. Needs a fix.

**Comment by droidmonkey** [comment]
This works well, no problems from me

**Review by droidmonkey — APPROVED** [review]

**Pull request merged**
