### PR TITLE
Add favicons for the tab

### PR DESCRIPTION
**Pull request by xf-**
IDE removed some trailing spaces

### CODE REVIEW

**Comment by droidmonkey** [comment]
Please include a full description for your change and screenshots. Additionally, move the "IDE removed some trailing spaces" to a different commit.

**Comment by xf-** [comment]
@droidmonkey i think @varjolintu added the most fixes. Only stuff left are the favicons (identify the tab on a full bar) and c&p button for to get the version information into the clipboard.

**Comment by varjolintu** [comment]
I would be easier to add those directly to my PR, wouldn't it?

**Comment by xf-** [comment]
@varjolintu if you like the adjustment/feature - take it :) Like we wrote on IRC, i created the PR basically to show possible changes/fixes instead of screenshots.

**Pull request closed without merging**
