### PR TITLE
WIP: perf: minimize `_locales` files

### PR DESCRIPTION
**Pull request by WofWca**
TODO: state `minimize-webext-i18n-json` as a dependency in package.json

This currently reduces the size of dist ZIPs by 14%

### CODE REVIEW

**Review by droidmonkey — APPROVED** [review]
as long as the translations still work, why not

**Comment by varjolintu** [comment]
Not sure if this is really needed. Just adds another dependency. The extension size is not a problem anyway.

**Comment by WofWca** [comment]
Well, that dependency is not that big either, so I'd say it's worth it. But I respect your decision.

I've still updated the branch so it's ready to be merged.

**Comment by varjolintu** [comment]
Instead of adding new dependencies, we should focus removing all possible ones instead. Especially when it comes to scripts that are ran locally.

**Comment by WofWca** [comment]
Off-topic, but just curious, why _especially_ the ones that are ran locally? Wouldn't client-side dependencies be more impactful?

**Comment by varjolintu** [comment]
Because those local scripts would be running on my (virtual) computer, modifying files.

**Pull request closed without merging**
