### PR TITLE
Translations from Transifex

### PR DESCRIPTION
**Pull request by varjolintu**
Added translations from Transifex.

Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/417.

WIP, because there are a few PR's that have some changes for the next version:
https://github.com/keepassxreboot/keepassxc-browser/pull/392
https://github.com/keepassxreboot/keepassxc-browser/pull/396

### CODE REVIEW

**Comment by varjolintu** [comment]
The messages.json has been updated to Transifex. Please translate the missing pieces so we can finally include this in the next build.

**Comment by phoerious** [comment]
Is this automated? If not, I'd suggest you add a script that pulls and pushes translations just like we have it for KeePassXC.

**Comment by varjolintu** [comment]
@phoerious No it's not. Good idea.

**Comment by varjolintu** [comment]
This PR is replaced by https://github.com/keepassxreboot/keepassxc-browser/pull/457.

**Pull request closed without merging**
