### PR TITLE
added German translation

### PR DESCRIPTION
**Pull request by nebulon42**

### CODE REVIEW

**Comment by droidmonkey** [comment]
Translations are done through transifex. Please go to https://www.transifex.com/keepassxc/keepassxc-browser/dashboard/

**Comment by nebulon42** [comment]
Was this mentioned somewhere? Would have been good to know beforehand.

**Comment by nebulon42** [comment]
Oh great, no more work to do. What a waste of time.

**Comment by droidmonkey** [comment]
Good point, I thought it was in the readme, but was not. Will add.

**Pull request closed without merging**
