### PR TITLE
Fill multiple single TOTP fields

### LINKED ISSUE #902: Support multiple TOTP fields in KeePassXC Browser plugin
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Add support for TOTP entry with multiple fields to the KeePassXC Browser plugin. ie. one field for each digit of the TOTP code .

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
I currently have one login with a TOTP entry that has multiple fields for the TOTP. If I copy the TOTP code from the KeePassXC database and paste it into the first field, the digits from the 2nd digit on move into the other fields and the TOTP validates.

If use the **Choose custom login fields** and set the first digit TOTP field as the TOTP field. I can then use the Alt-Shift-O shortcut key to paste the TOTP code, however it just sits there and does not validate. If I hit **enter** the TOTP code is cleared from the field. Also the **Validate** button is  "grayed-out" as it is inactive, so I cannot click it to validate.

image

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I am using Firefox 76.0.1 (64-bit).
It looks like the browser plugin is using an different method to paste the TOTP code in than the user's paste method. I am guessing this is what is causing the TOTP entry with the browser plugin to not work for multiple fields.

One possible solution would be to allow setting multiple TOTP entry fields, one for each digit of the TOTP code.

The account I have with mulitple fields for the entry of the TOTP at login is at [Infomaniak.com](https://login.infomaniak.com). It is possible to setup a free account there to test.

### PR DESCRIPTION
**Pull request by varjolintu**
Fixes #902.

### CODE REVIEW

**Comment by droidmonkey** [comment]
Is the totp fill icon show once and in a proper location for the segmented fields?

**Comment by varjolintu** [comment]
@droidmonkey At this point there's no icons on any of those six fields. Currently it only works from the context menu and from keyboard shortcut.

**Comment by droidmonkey** [comment]
Gotcha, maybe we can place the totp icon below or above the first input field

**Comment by varjolintu** [comment]
@droidmonkey Something like that yes. The single fields are often so small there's no room for an icon.

**Comment by varjolintu** [comment]
@droidmonkey I decided to add the icon to the right side of the segmented fields. Usually there's no space or some text at the left side or above/bottom. So, right side definitely seems a more logical choice.

Screenshot 2021-03-07 at 11 57 56

**Comment by droidmonkey** [comment]
This doesn't seem to work on Newegg or Binance:

image

image

Although it looks like Binance was coded by evil, nasty people.

**Comment by varjolintu** [comment]
@droidmonkey Uh oh. Time to do some more testing then.

**Comment by varjolintu** [comment]
@droidmonkey I added an extra check for `form.length === 6` if there's nothing found that indicates that the form is 2FA related. With my test page those two examples (Newegg and Binance) now worked. Can you confirm this works for you too with the actual sites? Thanks.

**Comment by varjolintu** [comment]
@droidmonkey More fixes made based on our previous conversation.

**Comment by droidmonkey** [comment]
Newegg still doesn't work, but binanace does!

**Comment by varjolintu** [comment]
@droidmonkey On my test page the TOTP fields work with or without username/password fields. I'll make a test account and see how the login flow can be improved.

**Comment by varjolintu** [comment]
@droidmonkey NewEgg is working fine for me.

**Review by droidmonkey — APPROVED** [review]
Still doesn't work in Newegg for me, but we can continue on

**Comment by varjolintu** [comment]
@droidmonkey Gotta try to solve it later. I have no idea why it works for me with both Edge and Firefox.

**Comment by varjolintu** [comment]
@OdinVex There's no standard way to do segmented TOTP fields. So if our default implementation cannot detect them, we need to add a exception for a certain site. The HTML code you pasted already helps testing it.

**Comment by dhanak** [comment]
> QNAP QTS Operating Systems don't work now that they've switched to 6 JavaShit inputs.
> 
> `<div class="input-field-ct"><input name="" type="text" maxlength="1" class="login_input" tabindex="1" autocapitalize="none" autocomplete="off"><input name="" type="text" maxlength="1" class="login_input" tabindex="1" autocapitalize="none" autocomplete="off"><input name="" type="text" maxlength="1" class="login_input" tabindex="1" autocapitalize="none" autocomplete="off"><input name="" type="text" maxlength="1" class="login_input" tabindex="1" autocapitalize="none" autocomplete="off"><input name="" type="text" maxlength="1" class="login_input" tabindex="1" autocapitalize="none" autocomplete="off"><input name="" type="text" maxlength="1" class="login_input" tabindex="1" autocapitalize="none" autocomplete="off"></div>`
> 
> For the sake of code and/or making it an easy fix, perhaps add TOTP1, TOTP2...TOTP6, and if TOTP isn't set but TOTP1...TOTP6 is, use those instead. Small documentation to mention?
> 
> Form is a multi "page" (CSS+JS-led) that has more than 6 length.

Yeah, I'm also facing this issue with QNAP logins. It used to work fine with a single field, I don't know why they had to go “smart” on this.

**Comment by droidmonkey** [comment]
Please file or send a comment into a bug report to QNAP.

**Comment by varjolintu** [comment]
Can you try the current develop branch of the extension? There's one fix made for the segmented TOTP field detection.

**Comment by varjolintu** [comment]
> > Can you try the current develop branch of the extension? There's one fix made for the segmented TOTP field detection.
> 
> I don't have a setup for building an XPI. 2021-2023, just noticed how long this Issue has been open. I temporarily worked around the issue by disabling Qnap's MFA and using a proxy page instead where I implemented it.

You don't need to build anything. You can just download the branch using git, or just the zip file. Then you can open the folder as a temporary extension to your browser:
https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually

**Comment by varjolintu** [comment]
@OdinVex There's already a feature request for it.

**Pull request merged**
