### PR TITLE
Add a copy button for version

### PR DESCRIPTION
**Pull request by xf-**
image

after pressing
image

and ctrl+v
```
KeePassXC - 2.5.3
KeePassXC-Browser - 1.5.4
Operating system: Linux x86_64
Browser: Mozilla Firefox 75.0
```

### CODE REVIEW

**Comment by droidmonkey** [comment]
Is it not possible to add the text directly to the clipboard instead of doing a select/copy operation? At least we should deselect when we are done.

**Comment by varjolintu** [comment]
That's what the password generator currently does. Just uses `.select()` for the input and then `document.execCommand('copy')`.

**Comment by xf-** [comment]
@droidmonkey not really. select is only possible on a input/textarea

**Comment by droidmonkey** [comment]
Can you deselect once done copying?

**Comment by varjolintu** [comment]
Btw, you could just use the following:
```
$('#copyVersionToClipboard').on('click', function () {
    const copyText = document.getElementById('versionInfo');
    navigator.clipboard.writeText(copyText.textContent);
});
```

**Comment by xf-** [comment]
adjusted it and innerText uses no spaces

now
```javascript
    $('#copyVersionToClipboard').on('click', function () {
        const copyText = document.getElementById('versionInfo').innerText;
        navigator.clipboard.writeText(copyText);
    })
```

**Pull request merged**
