### PR TITLE
✏️ (Context Menu) Consistency with other terms

### PR DESCRIPTION
**Pull request by kud**

### CODE REVIEW

**Comment by varjolintu** [comment]
FYI: This should be merged to `develop` branch.

**Comment by kud** [comment]
I think there is a kind of bug on the GitHub website as you correctly configure `develop` as the default branch, but when you edit a file from the web interface, it suggests `master` by default as the branch for your PR. I will report this to GitHub support. Thank you for letting me know.

**Comment by kud** [comment]
Here we go.

**Comment by varjolintu** [comment]
The "Fill attribute..." could be also changed to "Fill Attribute..."?

**Comment by varjolintu** [comment]
Rebase is needed.

**Review by varjolintu — APPROVED** [review]

**Pull request merged**
