### PR TITLE
Creates a window to show multiple credentials for HTTP authentication

### PR DESCRIPTION
**Pull request by varjolintu**
Creates a popup window for multiple credentials on HTTP basic authentication requests.

image

### CODE REVIEW

**Comment by pfoo** [comment]
Is there still hope of seeing this merged and released ?
It is a massive UI overhaul and will also allows to stop relying on automatic filling for HTTP authentication

**Comment by furious** [comment]
It's been an while, how is it going?

@varjolintu I think you should merge what we have, the problem you mentioned it isn't a major issue. It's better than having to always click on that extension icon to select one credential...

**Comment by varjolintu** [comment]
@furious A dead end for now. I gotta take a new look at this.

**Comment by varjolintu** [comment]
Gonna dump this one. I'll figure out something else.

**Pull request closed without merging**
