### PR TITLE
Updates Bootstrap library to version 5. Removes jQuery.

### PR DESCRIPTION
**Pull request by varjolintu**
Updates Bootstrap library from 4.4.1 to 5.1.3. This allows removing jQuery totally from the project. Options page and popups are now using vanilla JavaScript instead.

### CODE REVIEW

**Comment by droidmonkey** [comment]
image

Got this on load

**Review by droidmonkey — APPROVED** [review]
Works great, actually feels faster to me

**Comment by varjolintu** [comment]
> image
> 
> Got this on load

What..? Chromium browsers are already dealing these as errors and not warnings?

**Comment by Fuddl1** [comment]
There seem to be needless jQuery includes left over in 1.8.0. I assume those should also be remove:
```
fuddl@flutschi:~/debian/keepassxc-browser/keepassxc-browser$ grep -ri 'jquery' keepassxc-browser/
keepassxc-browser/content/ui.js:// jQuery style wrapper for querySelector()
keepassxc-browser/options/shortcuts.html:    <script src="../bootstrap/jquery-3.4.1.min.js"></script>
keepassxc-browser/popups/popup_httpauth.html:    <script src="../bootstrap/jquery-3.4.1.min.js"></script>
```

**Pull request merged**
