### PR TITLE
 TOTP filling fixes

### LINKED ISSUE #1311: Warning! OTP not found
Can't use OTP on AWS loging page by default. A warning box is displayed.

## Expected Behavior
I should be able to follow complete logging in process: enter user/password on first screen and then fill OTP by clicking on the KeePassXC icon in the OTP field.

## Current Behavior
Currently on the OTP page when clicking on the green icon I receive warning that no OTP was found ("Warning!No se ha encontrado TOTP.").
Surprisingly if I click on the KeePass toolbar icon and select one of the stored credentials (I have two) then clicking on the green icon in OTP field I get the pop-up to select credential that would source OTP.

It seems that afterwards it works just fine (close tab and re-login: each time the OTP selection is offered in the field)

## Possible Solution
The OTP credential selection should work immediately without the need to click on the toolbar icon.

## Steps to Reproduce (for bugs)
1. Go to AWS loging page (https://….signin.aws.amazon.com/console)
2. Enter credentials (username/password) on the first screen
3. click on the green icon in OTP field

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8.1
Operating system: MacIntel
Browser: Mozilla Firefox 87.0

### LINKED ISSUE #1328: Can't fill TOTP on gmx.net
TOTP can't be filled on gmx.net.
## Expected Behavior
I should be able to fill OTP by clicking on the KeePassXC icon in the OTP field or via context menu.

## Current Behavior
KeepassXC doesn't fill otp field consisting of multiple inputs.
grafik

## Possible Solution
Support otp fields with separated inputs?

## Steps to Reproduce (for bugs)
1. Sign in on gmx.net with 2FA enabled
2. Get redirected to 2FA screen
3. Try to fill TOTP via context menu or icon

## Debug info

`TypeError: kpxc.credentials[0] is undefined keepassxc-browser.js:1720:9`

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8.1
Operating system: Win
Browser: Firefox

### PR DESCRIPTION
**Pull request by varjolintu**
- Keeps the login ID for updating TOTP lists
- Fixes a check for credential list

Fixes #1311.
Fixes #1328.

### CODE REVIEW

**Review by droidmonkey — APPROVED** [review]
Yesssss!!!!

**Comment by varjolintu** [comment]
I still need to do some more testing, and ask the people from the issue thread to test this, as I couldn't reproduce every problem.

**Comment by gbsf** [comment]
This does _not_ fix #1311 for me. As I said in https://github.com/keepassxreboot/keepassxc-browser/issues/1311#issuecomment-855322618, there is a code path that does not set the login ID at all. Furthermore, the code below already uses the first credential in the `''` case, so there is no functional change that I can see.
 https://github.com/keepassxreboot/keepassxc-browser/blob/71491d9e9817b7810721ee0eaff5067578d00ce8/keepassxc-browser/content/keepassxc-browser.js#L1719-L1721

A fix for my problem is below, and I followed these steps to confirm:

1. Log in to a site using the drop-down, the OTP will be found;
1. Re-lock the database;
1. Log in to a different site _without_ using the drop-down, _i.e._ auto-filling credentials if there is only one entry; the OTP won't be found without my fix.

```diff
--- a/keepassxc-browser/content/keepassxc-browser.js
+++ b/keepassxc-browser/content/keepassxc-browser.js
@@ -898,6 +898,7 @@ kpxc.fillInFromActiveElement = async function(passOnly = false) {
             return;
         } else {
             // Just one credential -> fill the first combination found
+            await sendMessage('page_set_login_id', ''); // or kpxc.credentials[0].uuid
             kpxc.fillInCredentials(combination, kpxc.credentials[0].login, kpxc.credentials[0].uuid, passOnly);
             return;
         }
```

**Comment by varjolintu** [comment]
@gbsf Ah, I see! Thanks for the hint.

**Pull request merged**
