### PR TITLE
Added quick filter in popup

### PR DESCRIPTION
**Pull request by Ashus**
A new input field will show up if more entries are present in popup.
Search matches case insensitively any part of title, unlike autocomplete-like select.

### CODE REVIEW

**Comment by varjolintu** [comment]
Please use single quotation in the JavaScript code.

**Comment by Ashus** [comment]
I rebased it into one commit as requested.

**Comment by droidmonkey** [comment]
Please post a screenshot

**Comment by Ashus** [comment]
droidmonkey: keepassxc-browser-filter

**Comment by droidmonkey** [comment]
Cool! Thank you

**Pull request merged**
