### PR TITLE
Do not fill readonly fields

### LINKED ISSUE #1840: Readonly input boxes are filled with credentials
## Expected Behavior

I'm on OWA, trying to change the password for my account. I see this form:

image

KeePassXC offers to have credentials auto-filled here, which seems convenient enough to have my current password entered there. When I click the KeePassXC icon, I would expect my current password to be filled.

## Current Behavior

When I navigate to the form for the first time, my user name is already filled in and the textbox is readonly.

When I click the icon, my current password is filled in, but it also replaced the `Domain\user name` part in the readonly text input above it.

I'm not sure if this is even a problem, but I log in on the page with `user@domain.tld` and this input box displays/expects `domain\user`, which might be conflicting.

## Possible Solution

Don't change values already present in readonly text inputs.

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.4
Operating system: Win64
Browser: Chrome/Chromium 109.0.0.0

### PR DESCRIPTION
**Pull request by varjolintu**
Add a simple check for readonly fields.

Fixes #1840.

### CODE REVIEW

**Review by droidmonkey — APPROVED** [review]

**Comment by olifre** [comment]
Does this exclude fields actively selected by the user, i.e. the use case covered by https://github.com/keepassxreboot/keepassxc-browser/pull/878 (see https://github.com/keepassxreboot/keepassxc-browser/issues/818 )?

**Comment by varjolintu** [comment]
@olifre Yes. This doesn't allow filling readonly fields even if those are selected via Custom Login Fields.

**Comment by olifre** [comment]
@varjolintu Thanks for the quick reply!

So that means it actually breaks the use case described in https://github.com/keepassxreboot/keepassxc-browser/issues/818#issuecomment-602271323 : Filling readonly Custom Fields, which are usually filled by javascript via user interaction, e.g. pin entry fields with numbers to click on, is not possible anymore, correct?

**Comment by varjolintu** [comment]
@olifre Seems so. Gotta fix this regression before the next release.

**Comment by olifre** [comment]
@varjolintu Thanks, that will be indeed be helpful :+1: .

**Comment by varjolintu** [comment]
@olifre I'd suggest that we allow filling String Fields using Custom Login Fields also to readonly fields, but not username/password.

**Comment by olifre** [comment]
@varjolintu That seems very reasonable, I don't know any form which would mark username or password read-only but expect users to fill it indirectly via javascript. The only cases I do know are all additional Custom Login Fields (pin codes etc.), so the proposal to allow filling readonly String Fields iff they are Custom Login Fields would work well. :+1:

**Comment by pdinc-oss** [comment]
Oh this breaks iDRAC v9 (Dell) logins

**Pull request merged**
