### PR TITLE
Add TOTP icon filling and improve icon handling

### PR DESCRIPTION
**Pull request by varjolintu**
This is an extension to #617.

New features:
- Adds a new OTP icon for filling
- Adjusts icon saturation based on database lock status (password and OTP icons are grey)

When DB is locked:
closed

When open:
open

### CODE REVIEW

**Comment by droidmonkey** [comment]
We are introducing a key icon again?

**Comment by varjolintu** [comment]
Nope. It's just enabled for the screenshot. Still disabled by default.

**Comment by droidmonkey** [comment]
Some findings for various popular websites that use different id's for their TOTP field:

* Twitter: `challenge_response`
* Google: `totpPin`
* Turbotax: `ius-mfa-soft-token`
* Amazon AWS: `mfaCode`

I found that sometimes the OTP field was misidentified as a username field when you have the site setup as username-only detection. There should be some workflow tracking to not propose another username fill AFTER the password is filled. Even a simple flag of "hasPasswordBeenFilled" would suffice to not re-propose a username fill.

**Comment by varjolintu** [comment]
@droidmonkey Good findings. It's clear that we cannot support all possible ID's there are, but at least fields containing `challenge`, `mfa`, `2fa` or `token` could be added to the list. And you are correct about the another username fill happening. I will make some changes to this PR. I don't want to rush it.

**Comment by droidmonkey** [comment]
Yah good idea, that that should cover the majority of cases.

**Comment by varjolintu** [comment]
Changes made. I tested the TOTP field using Username-only Detection enabled for GMail and Mastodon. Both worked fine.

**Comment by grenzor** [comment]
Been checking some websites I visit and noticed OTP field IDs that contain `code` and `auth` more than once (with differences in uppercase/lowercase, not sure if that matters here). Could they be added to the list? Seems to me like they could be somewhat common.

**Comment by varjolintu** [comment]
@grenzor Those could be added also. Just noticed the comparison is currently not made with lowercase. Gotta fix that too.

**Comment by varjolintu** [comment]
Plus, I will make showing the icon optional (enabled by default), just like the other icons.

**Comment by grenzor** [comment]
`2fa` removed and `otp` listed twice. Mistake?

**Comment by varjolintu** [comment]
Ah, bad copy paste. Fixed.

**Pull request merged**
