### PR TITLE
Custom Login Fields fixes

### LINKED ISSUE #957: detect textarea as input field
Some websites like QNAP NAS Webinterface using `<textarea .../> elements rather than `<input ... />` as username or password fields. Currently, KeePassXC does not detect textarea elements.

Example:

```html
<textarea class="qStr" data-qstrph="LDAP_SERVER_STR12" id="username" autocomplete="off" placeholder="Benutzername"></textarea>
```

### LINKED ISSUE #1109: HMI bug on fields manual settings
## Expected Behavior

A menu is displayed in a dark division above the login page of the site where i want to manually select the fields.
This menu contains a title that describe the current field the user must select, a description of some keyboard shortcut and some buttons to control the operation.
The division end after the buttons.

## Current Behavior

A menu is displayed in a dark division above the login page of the site where i want to manually select the fields.
This menu contains only a title but no other contents.
The division has no ending on screen.
KeePassXC - HMI Bug on fields detection

## Steps to Reproduce (for bugs)

1. Get to the URL: https://saintmartindheres.espace-famille.net/saintmartindheres/index.do
2. From the KeePassXC-Browser menu, select "Custom Id fields".

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Windows 10
Browser: Firefox 82.0.3

### LINKED ISSUE #1112: Username field of bitrise.io not detected
## Expected Behavior

The "Email or Username" field on https://app.bitrise.io/users/sign_in should be detected properly.
Currently it's not even possible to select it as custom input field.
image

## Current Behavior

The field is not detected automatically.

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Linux
Browser: Chromium

### PR DESCRIPTION
**Pull request by varjolintu**
- Allows selecting input fields with less restrictions with `More` option
- Restricts setting the height of internal divs

Fixes #957.
Fixes #1109.
Fixes #1112

### CODE REVIEW

**Comment by droidmonkey** [comment]
Still seems to have problems:
image

**Comment by varjolintu** [comment]
@droidmonkey This PR fixes the problem with `More` option. That site is a good example because it didn't work with the previous version. Now, if you press `More` you can select the username field normally. It's not detected by default because its type is non-standard `undefined`

**Comment by droidmonkey** [comment]
Ahhh gotcha

**Comment by varjolintu** [comment]
@droidmonkey I just noticed your edited message. A dedicated button would be a nice addition.

**Review by droidmonkey — APPROVED** [review]

**Pull request merged**
