### PR TITLE
Add dev info in README.md

### PR DESCRIPTION
**Pull request by h-h-h-h**
I wrote this while trying to create a build to test the changes for issue #600. Anything overcomplicated or imperfect?

### CODE REVIEW

**Comment by varjolintu** [comment]
There's already one instruction available: https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually

And actually you don't need to build the extension at all if you want to test it and load it as a temporary extension. The building is only "needed" for deployment because Firefox and Chromium versions differ slightly. At this point the only difference is that when building a Firefox version, all the extension icons are replaced with SVG, while Chromium doesn't support those.

**Comment by h-h-h-h** [comment]
Then, this page or the wiki in general should be linked in README.md. Is some of the information I wrote still relevant for working on the code? How should it be changed?

**Comment by varjolintu** [comment]
I think linking to that wiki article could be enough in the README, but that section with installing the extension to Firefox with signatures disabled would be a nice addition it.

**Comment by h-h-h-h** [comment]
This would be the markdown to add to the wiki page. Adjust heading levels as appropriate:

````md
## Build extension into .zip file and load

### Prerequisites

- Run `npm install`.
- Install the [Transifex CLI tool](https://github.com/transifex/transifex-client#installation).
- Log into Transifex (e.g., with your GitHub account), click "Join team" on [this page](https://www.transifex.com/keepassxc/keepassxc-browser/) and, after a page reload, make sure "KeePassXC" is the active organization in the drop-down box on the top of the page.
- Go to your Transifex user settings, generate an API token, give it a name associating it with KeePassXC and [save it in your config file](https://docs.transifex.com/client/client-configuration).

### Building

Run `npm run build`.

### Installing

#### Firefox

- Visit `about:config` and set `xpinstall.signatures.required` to `false`. This requires ESR, Developer Edition or Nightly. (Remember to undo this.)
- Visit `about:addons`.
- Go to the custom add-on settings and export a backup.
- Uninstall the add-on.
- Click the gear button, "Install Add-on From File..." and choose the built .zip file for Firefox.
- Restart the browser and connect your database via the settings.

**Comment by varjolintu** [comment]
Thank you! The title for README could be "Development and testing".

**Comment by varjolintu** [comment]
Rebase and we are done.

**Comment by h-h-h-h** [comment]
Rebase? I used GitHub's online editor to edit README.md from the branch "develop".

Are you referring to the little artifact-like changes? That was me. It's just little corrections.

**Comment by varjolintu** [comment]
Meaning squashing the commits. Three commits for such a small fix is bit too much :)

**Pull request closed without merging**
