### PR TITLE
fix "Reload" button unaccessible from pinned popup

### PR DESCRIPTION
**Pull request by dym-sh**
## problem
when the extension is "pinned" to the overflow menu – the popup is constrained within the smaller window, hence not all elements on it are even visibly exist, let alone accessible:
before

and only visible+accessible after pressing [Tab]:
before onKey Tab

## solution
just **_don't_** align buttons to the right for "esthetic" reasons:

after

### CODE REVIEW

**Comment by droidmonkey** [comment]
This looks like a bug in edge browser

**Comment by varjolintu** [comment]
Firefox also has had a similar issue where the popup size is not respected.

**Comment by dym-sh** [comment]
it is firefox, and this is supposedly a feature – where popups of pinned addons are limited by the enclosing submenu

**Comment by varjolintu** [comment]
I would assume a proper fix for this should be to just set the popup width to automatic, but keep the maximum width intact. Then the content is just scaled like it should be.

**Comment by dym-sh** [comment]
sure, that works too:

**Comment by varjolintu** [comment]
@dym-sh That won't work. Now it breaks the normal popup, plus it looks completely different in Firefox.

**Comment by dym-sh** [comment]
is this enough of a compromise?

upd_20220125062450

**Comment by varjolintu** [comment]
@dym-sh I'd prefer if the layout doesn't change from the current one when normal popup is used. This PR should only solve problems when the popup is not wide enough for the content.

**Comment by dym-sh** [comment]
tfw> vendors change their own defaults creating obscure edge cases, and then never address the arised issues

/ref https://bugzilla.mozilla.org/show_bug.cgi?id=1373490

**Comment by varjolintu** [comment]
It' still not working with Firefox:
Screenshot 2022-01-25 at 19 37 18
Screenshot 2022-01-25 at 19 37 07

Not sure if it's even fixable due the Firefox bug.

**Comment by dym-sh** [comment]
so remember how i simply removed the right-align style – lets just keep that?

you also can add this line to `popup.js` and see exactly how it differs on every fractional dpi setting: 302, 194, or sometimes 0. :hankey:

```diff
diff --git a/keepassxc-browser/popups/popup.js b/keepassxc-browser/popups/popup.js
index ef20c28..cc1aa27 100644
--- a/keepassxc-browser/popups/popup.js
+++ b/keepassxc-browser/popups/popup.js
@@ -111,5 +111,5 @@ $(async () => {
     }).catch((err) => {
         console.log('Error: Could not get status: ' + err);
     }));
+    document.getElementById('reload-status-button').innerText = window.innerWidth;
 });
```

**Comment by varjolintu** [comment]
As said before, that still doesn't fix the content issues with e.g. `popup_login.html`:
Screenshot 2022-01-26 at 9 51 49

**Comment by dym-sh** [comment]
well this needs complete re-flow of the layout if you want to still fit it in the 300px popup, but you didnt want 2 rows of top buttons either?

**Comment by varjolintu** [comment]
Yup.. If this is going to be fixed, let's fix it properly.

**Comment by varjolintu** [comment]
Replaced by: https://github.com/keepassxreboot/keepassxc-browser/pull/1571.

**Pull request closed without merging**
