### PR TITLE
Add fidelity.com to Predefined Sites

### LINKED ISSUE #1083: Cannot fill in username on www.fidelity.com, even after choosing custom login fields
## Expected Behavior
The login form on www.fidelity.com should allow filling the username field either via the normal drop-down, or by right-click "Fill username or password". At worse case, this should happen after choosing custom login fields.

## Current Behavior
Even after choosing custom login fields and forcing a page refresh or new tab, the username field cannot be filled. However, the password field can be filled.

## Steps to Reproduce (for bugs)

1. Create a keepass entry for https://www.fidelity.com
2. Go to https://www.fidelity.com
3. Try clicking on username field, a drop down should not appear.
4. Try right clicking on username field and choosing "Fill username or password". It should not be filled.
5. Try choosing custom login fields, and forcing refresh or open a new tab. The dropdown should not appear, and choosing "Fill username or password" should not work either.

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.2
Operating system: Linux
Browser: Firefox

### PR DESCRIPTION
**Pull request by varjolintu**
Fixes #1083.

### CODE REVIEW

**Comment by varjolintu** [comment]
Hold on a sec, I'll try a few more things to get this better.

**Comment by varjolintu** [comment]
@droidmonkey This is good to go. It also increases the version number.

**Review by droidmonkey — APPROVED** [review]

**Comment by weiw11** [comment]
This doesn't appear to be working when user has "Remember me" selected. Is it possible to change the class selection to id?

With remember me selected, `fs-mask-username` is not in the class as it uses a selection instead.

With "remember me" selected, we can use `userId-select`
```html
<select id="userId-select" class="fs-hidden" aria-hidden="true" name="SSN" required="required" aria-required="true" data-reset-text="Use a saved username" tabindex="1" disabled="disabled">
   <option value="new">Add/Use another username</option>
</select>
```

Without "remember me" selected, we can use `userId-input` instead
```html
<input class="fs-mask-username fs-nounmask" autocomplete="off" aria-hidden="false" aria-required="true" id="userId-input" value="" type="text" maxlength="15" required="required" aria-describedby="fs-user-info" data-masklength="-3" data-clear="true" data-msg-required="Please enter your username" data-msg-invalid="This field is not properly formatted" tabindex="1" data-unmasked="weiw95">
```

**Comment by varjolintu** [comment]
> This doesn't appear to be working when user has "Remember me" selected. Is it possible to change the class selection to id?

It's possible. Let me tune this a little bit. Thanks for letting us know.

**Comment by varjolintu** [comment]
@weiw11 I made a PR that fixes the Custom Login Fields selection for the site: https://github.com/keepassxreboot/keepassxc-browser/pull/1394

**Pull request merged**
