### PR TITLE
[WIP] Allow filling attributes to fields from context menu

### PR DESCRIPTION
**Pull request by tremby**
I decided to have a shot at implementing #390.

This is tested so far only in Firefox.

I request feedback, please.

I reworked how the context menu is built slightly, to allow arbitrary context menu item options to be passed in, and to allow arbitrary arguments to be sent along with the action, and to allow reuse of the logic which converts from the terse form of an item to the options object passed to the browser.

Questions:

1. How are other languages usually populated? Should I start off by just grabbing translations from Google Translate?
2. How should I be handling multiple sets of credentials here? I'm currently assuming there's exactly one set, and so grabbing the first one. Please give some guidance.
3. Am I running the credentials retrieval and context menu rebuilding code correctly and at the right time? See `background/init.js`.
4. Right now it's using the `KPH` attributes, since these are the only ones I seem to be able to get from Keepassxc. Am I right in saying a change to Keepassxc is needed to get others? I personally would like it to offer me *all* the attributes in this context menu; I'd rather not have to prefix them to appear here, I think. If a change is necessary, can you help guide me on that, please? My C++ is beginner-level.
5. Am I handling the attributes correctly? I don't understand why they're retrieved as an array of objects, each with one key in it. It necessitates a pretty ugly reduce call to get them all into one object so I can get the one I'm looking for or loop through them conveniently.
6. Any thoughts about what the menu structure should be?
7. What does KPH stand for? I'm guessing the KP is Keepass...

To do:

- ~Add "Fill attribute…" message in locales other than English~
- [ ] Properly handle multiple sets of credentials
- [ ] Ensure I'm running the credentials retrieval and context menu rebuilding code correctly and at the right time
- ~Get *all* attributes, or ones with a special new prefix other than `KPH: `, since this isn't what those are for~
- [x] Ensure I'm handling the attributes correctly
- [x] Finalize menu structure
- [ ] Test in Chrome

### CODE REVIEW

**Comment by varjolintu** [comment]
1. Translations are done via [Transifex](https://www.transifex.com/keepassxc/keepassxc-browser/)

2. This is problematic. Now you are doing an extra `retrieveCredentials` on tab activation and this is not a good thing. `kpxc.retrieveCredentialsCallback()` is the place for this. But because it's handled in the content script (I'd like to move this to the background script instead actually..), you'll have to send message to the background script where the context menu changes are made. This will automatically allow you to pass multiple credentials to the function that updates the context menu.

3. Like told above, no, you are not.

4. Attributes starting with `KPH` are the one you must use here. We have no need to change those.

5. This may not be the best implementation for this, and I agree it could be much better.

6. An menu item with a submenu containing the attributes.

7. I think it's originally just a short form for KeePassHTTP.

**Comment by tremby** [comment]
> But because it's handled in the content script (I'd like to move this to the background script instead actually..), you'll have to send message to the background script where the context menu changes are made.

Is this your recommended approach for now?

If so, can you please point me in the right direction for how to get the data across -- how to send and receive the message in this direction? I may be missing something but I don't see that happening elsewhere, at least not into the `init.js` file, where the context menu stuff is.

> Attributes starting with `KPH` are the one you must use here. We have no need to change those.

OK. I'd really like to be able to pass arbitrary ones, but I suppose that can be a separate request, and of course would be against the main application's repo rather than here.

> This may not be the best implementation for [the attributes data structure], and I agree it could be much better.

I suppose I won't rock the boat for this patch, but maybe will try to improve it separately later.

> An menu item with a submenu containing the attributes.

This sounds like what I have at the moment is fine, then:

```
+----------------------------------+
|               ...                |
| Inspect element                  |
| Inspect accessibility properties |
+----------------------------------+----------------------------+
| KeePassXC-Browser              > | Fill Username and Password |
+----------------------------------+ Fill Password Only         +-----------------------+
                                   | Fill attribute...        > | Childhood best friend |
                                   | Fill TOTP                  | Dream job as a child  |
                                   | Show Password Generator    | Favourite teacher     |
                                   | Save credentials           +-----------------------+
                                   +----------------------------+
```

Let me know if not.

**Comment by tremby** [comment]
I made an account on Transifex but don't seem able to (even request to) join the xeepassxc-browser team. It needs me to select a language to translate to, but I think all I want to do is add this new string. So it's not clear to me what the process is here.

Still hoping for guidance on how to listen for and respond to credentials having been retrieved, from the `background/init.js` file too.

**Comment by phoerious** [comment]
You do not need to add source strings on Transifex. That will happen automatically next time we sync the translations with Transifex.

**Comment by varjolintu** [comment]
Replaces by #1023.

**Pull request closed without merging**
