### PR TITLE
Support for Manifest V3

### LINKED ISSUE #1581: Support for Manifest V3
## Expected Behavior

The extension should support Manifest V3. The final deadline is January 2023 when Google no longer allows updating existing extension to Chrome Web Store if only Manifest V2 is present:
https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/

Migration checklist: https://developer.chrome.com/docs/extensions/mv3/mv3-migration-checklist/
Mozilla's migration guide: https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/

The following are affected:
- Replace the webRequestBlocking permission with declarativeNetRequest. Probably only affects Chromium based browsers.
- `browser.runtime.getBackgroundPage()` will not work. [Service workers](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/) must be used instead.
- `content_security_policy` must be replaced.
- Using inline scripts or styles is no longer possible. Investigate if [Scripting API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting) can be used instead.
- Make a separate manifest for Firefox and update the install script

### PR DESCRIPTION
**Pull request by varjolintu**
Adds support for Manifesft V3 for Chromium based browsers. Firefox will be still supporting the V2 version.
V2 manifest is still used as default. Only when building the extension, Chromium will switch to V3 instead.

The manifest configuration will be the following:
- The root `keepassxc-browser` path contains a "common" `manifest.json` file that can be loaded directly with Firefox, and it should also support Chromium based browsers for now.
- New `dist/` path contains separate manifest files for both browsers. Firefox will remain with V2. These are only used when building packages for release.

Progress:
- [x] A working Chromium version
- [x] A working Firefox version (V2)
- [x] Some API functions (e.g. `setIcon`) must differ when using Firefox
- [x] HTTP Basic Auth support is not implemented with Manifest V3 API's (see: https://bugs.chromium.org/p/chromium/issues/detail?id=1135492)
- [x] Fill attribute does not work (`onclick` is no longer accepted when creating a new context menu item)
- [x] Update build scripts, and keep a working Manifest V2 file in the root folder.
- [x] Fix inline scripts from popups and options page
- [x] Replace `XMLHttpRequest` with `fetch()`
- [x] Basic testing (Passkeys, credential filling, password generator etc..)

Fixes #1581.

### CODE REVIEW

**Comment by jsachs** [comment]
Is there any timeline for when this PR will be merged? The manifest v2 sunset begins this week: https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/

**Comment by varjolintu** [comment]
> Is there any timeline for when this PR will be merged? The manifest v2 sunset begins this week: https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/

No it doesn't: https://groups.google.com/a/chromium.org/g/chromium-extensions/c/zQ77HkGmK9E

"Expect to hear more about the updated phase-out plan and schedule by March of 2023."

**Comment by varjolintu** [comment]
https://developer.chrome.com/blog/resuming-the-transition-to-mv3/

> We will begin disabling Manifest V2 extensions in pre-stable versions of Chrome (Dev, Canary, and Beta) as early as June 2024, in Chrome 127 and later. Users impacted by the rollout will see Manifest V2 extensions automatically disabled in their browser and will no longer be able to install Manifest V2 extensions from the Chrome Web Store. Also in June 2024, Manifest V2 extensions will lose their Featured badge in the Chrome Web Store if they currently have one.

**Comment by varjolintu** [comment]
This is done, except the inline scripts from `options.html` and `popup.html` might not work as expected with V3. There are some errors in the JavaScript console.

**Comment by varjolintu** [comment]
Ready for review. Testing this requires building the extension and loading it temporarily.

**Comment by droidmonkey** [comment]
Got an error on load:

image

Also, should include either a script or modify the README to describe the requirement to load manifest_chromium vs manifest_firefox

**Comment by droidmonkey** [comment]
After some testing:
* TOTP button didn't appear on twitter or paypal (using right click menu worked fine though)
* AWS sign in is still haphazard with showing buttons
*
Otherwise worked fine for me. I didn't test HTTP Basic Auth.

**Comment by varjolintu** [comment]
> After some testing:
> 
>     * TOTP button didn't appear on twitter or paypal (using right click menu worked fine though)
> 
>     * AWS sign in is still haphazard with showing buttons
> 
> 
> Otherwise worked fine for me. I didn't test HTTP Basic Auth.

Thanks. I'll try to get all possible issues fixed asap.

**Comment by droidmonkey** [comment]
I've been using Manifest v3 for a week now and no issues so far.

**Comment by varjolintu** [comment]
I still found one bug from this. It happens when your database is open and you lock it. The extension will lose the connection. Trying to solve it asap.

**Comment by droidmonkey** [comment]
Let's merge this PR and focus on fixing that problem next

**Comment by varjolintu** [comment]
I'll move this to 1.9.0 and focus on releasing a fix with the iframe stuff.

**Review by droidmonkey — APPROVED** [review]

**Comment by droidmonkey** [comment]
Did you implement the new onAuthRequired?

https://issues.chromium.org/issues/40723650#comment95

**Comment by varjolintu** [comment]
> Did you implement the new onAuthRequired?
> 
> https://issues.chromium.org/issues/40723650#comment95

Yes, the HTTP Basic Auth works now.

**Pull request merged**
