### PR TITLE
Add "2fpin" to acceptedOTPFields to fix #1291

### LINKED ISSUE #1291: Fill TOTP not working with Jira
## Expected Behavior
Fill in TOTP when right clicking in the TOTP field and then clicking "fill TOTP" with the KeepassXC browser extension. Note that this started happening just recently (may be caused by a Jira Server version update - but I can not say for sure). Unfortunately I also can't use the "detect custom input fields" wizard, because I can't get it to work with pages where the TOTP is on a new page.

## Current Behavior

Nothing happens.

## Possible Solution

-

## Steps to Reproduce (for bugs)

1. Log in to a Jira-Server (self-hosted) instance with 2FA Plugin installed and enabled
2. Fill Username + Password with the KeepassXC Browser extension
3. On the new page right click in the TOTP field and select "Fill TOTP" with the KeepassXC

## Debug info

KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.1-unknown

KeePassXC-Browser - KeePassXC-Browser-Version: 1.7.7
Operating system: Win
Browser: Chrome

### PR DESCRIPTION
**Pull request by amiga23**
Tested with web-ext, works fine

### CODE REVIEW

**Comment by varjolintu** [comment]
I'm curious. What page has this one? It's good to save to for a possible issue search.

**Comment by amiga23** [comment]
To be honest I can't really tell you. It is some 2FA plugin for Atlassian Tools (Jira and Confluence) I don't know which one exactly.

**Comment by varjolintu** [comment]
So this fixes https://github.com/keepassxreboot/keepassxc-browser/issues/1291?

**Comment by amiga23** [comment]
Seems to be this plugin: https://marketplace.atlassian.com/apps/1213472/secure-login-2fa-jira?hosting=server&tab=overview

**Comment by amiga23** [comment]
> So this fixes #1291?

You're right, can't say for sure that it fixes #1291 as there is not stated which plugin is used. But it fixes the issue with the plugin I mentioned above.

**Review by varjolintu — APPROVED** [review]

**Review by droidmonkey — APPROVED** [review]

**Pull request merged**
